Repository openshift/prometheus, pull requests merged in 2018-11, with the labels that each got.

#15 add owners file to allow automated pr approval and merges
  OWNERS
Labels: size/XS

#16 Use multistage build for upstream image generation
  Dockerfile
Labels: lgtm, size/S

#17 Add OWNERS file and Dockerfile
  Dockerfile
  OWNERS
Labels: lgtm, size/M
