Repository openshift/prometheus, pull requests merged in 2019-01, with the labels that each got.

#21 Install promu package for OCP multistage builds
  Dockerfile.rhel
Labels: lgtm, size/XS

#20 Dockerfile: Remove VOLUME instruction
  Dockerfile
  Dockerfile.rhel
  Dockerfile.rhel7
Labels: lgtm, ok-to-test, size/S

#22 Dockerfile cleanup
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/S
